import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';

export interface Return {
  id: string;
  return_number: string;
  date: string;
  party_id: string;
  party_name: string;
  product_id: string;
  product_name: string;
  quantity_returned: number;
  unit_price: number;
  total_amount: number;
  reason?: string;
  status: string;
  created_at: string;
  updated_at: string;
  created_by?: string;
}

export interface CreateReturnData {
  party_id: string;
  party_name: string;
  product_id: string;
  product_name: string;
  quantity_returned: number;
  unit_price: number;
  reason?: string;
  date?: string;
  return_number?: string; // Optional since it's auto-generated
}

export interface UpdateReturnData {
  party_id?: string;
  party_name?: string;
  product_id?: string;
  product_name?: string;
  quantity_returned?: number;
  unit_price?: number;
  reason?: string;
  date?: string;
  status?: string;
}

export const useReturns = () => {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  // Fetch all returns
  const { data: returns, isLoading, error } = useQuery({
    queryKey: ['returns'],
    queryFn: async (): Promise<Return[]> => {
      const { data, error } = await supabase
        .from('returns')
        .select('*')
        .order('date', { ascending: false });
      
      if (error) throw error;
      return data || [];
    },
  });

  // Create return
  const createReturn = useMutation({
    mutationFn: async (returnData: CreateReturnData): Promise<Return> => {
      // Prepare data with return_number (will be auto-generated by trigger)
      const insertData = {
        ...returnData,
        return_number: '', // Will be auto-generated by database trigger
      };
      
      const { data, error } = await supabase
        .from('returns')
        .insert(insertData)
        .select()
        .single();
      
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['returns'] });
      queryClient.invalidateQueries({ queryKey: ['products'] });
      queryClient.invalidateQueries({ queryKey: ['inventory_transactions'] });
      toast({
        title: "Success",
        description: "Return processed successfully",
      });
    },
    onError: (error: any) => {
      toast({
        title: "Error",
        description: error.message || "Failed to process return",
        variant: "destructive",
      });
    },
  });

  // Update return
  const updateReturn = useMutation({
    mutationFn: async ({ id, ...updateData }: UpdateReturnData & { id: string }): Promise<Return> => {
      const { data, error } = await supabase
        .from('returns')
        .update(updateData)
        .eq('id', id)
        .select()
        .single();
      
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['returns'] });
      queryClient.invalidateQueries({ queryKey: ['products'] });
      queryClient.invalidateQueries({ queryKey: ['inventory_transactions'] });
      toast({
        title: "Success",
        description: "Return updated successfully",
      });
    },
    onError: (error: any) => {
      toast({
        title: "Error",
        description: error.message || "Failed to update return",
        variant: "destructive",
      });
    },
  });

  // Delete return
  const deleteReturn = useMutation({
    mutationFn: async (id: string): Promise<void> => {
      const { error } = await supabase
        .from('returns')
        .delete()
        .eq('id', id);
      
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['returns'] });
      queryClient.invalidateQueries({ queryKey: ['products'] });
      queryClient.invalidateQueries({ queryKey: ['inventory_transactions'] });
      toast({
        title: "Success",
        description: "Return deleted successfully",
      });
    },
    onError: (error: any) => {
      toast({
        title: "Error",
        description: error.message || "Failed to delete return",
        variant: "destructive",
      });
    },
  });

  return {
    returns,
    isLoading,
    error,
    createReturn,
    updateReturn,
    deleteReturn,
  };
};