// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyktxwttsjezibkzhqit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5a3R4d3R0c2plemlia3pocWl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzODY1MzYsImV4cCI6MjA2OTk2MjUzNn0.Lzdbyc3a0rsER6pR_W04tQUEpH-bATMH_4LIiJaSjIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});